### ISSUE TITLE
bug: 创建新仓库 出错

### ISSUE THREAD

**Issue by FXTD-ODYSSEY** [tiddly-gittly/TiddlyGit-Desktop#106]
## Environment

TG Version 0.4.4

Electron Version: 

Node Version:

Chromium Version:

OS (macOS, Windows, Linux) and Version: Windows

## Description:

![image](https://user-images.githubusercontent.com/40897360/133120395-592d7387-61a7-4143-bf8e-d9e5efa7df47.png)

创建新仓库 出错
已经将所有的 token 权限加上了
Windows 系统下

**Comment by linonetwo** [comment]
应该是因为你选择的 github 仓库里面已经有东西了。如果创建新仓库，必须选择空仓库来推上去。

**Comment by FXTD-ODYSSEY** [comment]
我选择创建新仓库也不行，仓库上传了一个 奇奇怪怪的文件

https://github.com/FXTD-ODYSSEY/tiddlygit-pkm

**Comment by linonetwo** [comment]
是有点奇怪，我也试试看。你可以加个 QQ 群来讨论下。

**Comment by linonetwo** [comment]
<img width="634" alt="截屏2021-09-20 19 48 53" src="https://user-images.githubusercontent.com/3746270/133997315-fbc04973-59de-4155-96bd-7c0ae16396a3.png">
我复现了，这个假期我修一下。

**Comment by linonetwo** [comment]
{"handler":"wiki-create-progress","callerFunction":"initWikiGit","functionName":"initGit","step":"StartGitInitialization","level":"notice","message":"开始初始化本地 Git 仓库","timestamp":"2021-09-20T11:48:36.812Z"}
{"handler":"wiki-create-progress","callerFunction":"initWikiGit","functionName":"initGit","step":"StartConfiguringGithubRemoteRepository","level":"notice","message":"仓库初始化完毕，开始配置 Git 云端仓库","timestamp":"2021-09-20T11:48:37.692Z"}
{"handler":"wiki-create-progress","callerFunction":"initWikiGit","functionName":"initGit","step":"StartBackupToGitRemote","level":"notice","message":"正在将 Wiki 所在的本地 Git 备份到 Github 云端仓库，需要的时间取决于网速，请耐心等待","timestamp":"2021-09-20T11:48:38.136Z"}
{"message":"FileSystemPaths.tid changed, but lock is on, so skip","level":"info","timestamp":"2021-09-20T11:48:39.117Z"}
{"message":"subwiki/calendar changed, but lock is on, so skip","level":"info","timestamp":"2021-09-20T11:48:40.300Z"}
{"handler":"wiki-create-progress","callerFunction":"initWikiGit","functionName":"initGit","step":"GitPushFailed","level":"notice","message":"Git上传的结果不佳，这通常意味着有网络问题","timestamp":"2021-09-20T11:48:41.062Z"}
{"message":"E-3 failed to config git to successfully pull from or push to remote with configuration {\"dir\":\"/Users/linonetwo/Desktop/calendar\",\"remoteUrl\":\"https://github.com/linonetwo/calendar\",\"syncImmediately\":true,\"userInfo\":{\"gitUserName\":\"linonetwo\",\"email\":\"linonetwo012@gmail.com\",\"accessToken\":\"gho_e85FDD9sbzvUEHCd9...\"},\"defaultGitInfo\":{\"email\":\"tiddlygit@gmail.com\",\"gitUserName\":\"tiddlygit\"},\"logger\":{}}.\nerror: src refspec master does not match any\nerror: failed to push some refs to 'https://github.com/linonetwo/calendar.git'\n","level":"error","timestamp":"2021-09-20T11:48:41.261Z"}
{"message":"↑Translated→: E-3 failed to config git to successfully pull from or push to remote with configuration {\"dir\":\"/Users/linonetwo/Desktop/calendar\",\"remoteUrl\":\"https://github.com/linonetwo/calendar\",\"syncImmediately\":true,\"userInfo\":{\"gitUserName\":\"linonetwo\",\"email\":\"linonetwo012@gmail.com\",\"accessToken\":\"gho_e85FDD9sbzvUEHCd9...\"},\"defaultGitInfo\":{\"email\":\"tiddlygit@gmail.com\",\"gitUserName\":\"tiddlygit\"},\"logger\":{}}.\nerror: src refspec master does not match any\nerror: failed to push some refs to 'https://github.com/linonetwo/calendar.git'\n","level":"error","timestamp":"2021-09-20T11:48:41.261Z"}
{"message":"initWikiGitTransaction failed, E-3 failed to config git to successfully pull from or push to remote with configuration {\"dir\":\"/Users/linonetwo/Desktop/calendar\",\"remoteUrl\":\"https://github.com/linonetwo/calendar\",\"syncImmediately\":true,\"userInfo\":{\"gitUserName\":\"linonetwo\",\"email\":\"linonetwo012@gmail.com\",\"accessToken\":\"gho_e85FDD9sbzvUEHCd9...\"},\"defaultGitInfo\":{\"email\":\"tiddlygit@gmail.com\",\"gitUserName\":\"tiddlygit\"},\"logger\":{}}.\nerror: src refspec master does not match any\nerror: failed to push some refs to 'https://github.com/linonetwo/calendar.git'\n GitPullPushError: E-3 failed to config git to successfully pull from or push to remote with configuration {\"dir\":\"/Users/linonetwo/Desktop/calendar\",\"remoteUrl\":\"https://github.com/linonetwo/calendar\",\"syncImmediately\":true,\"userInfo\":{\"gitUserName\":\"linonetwo\",\"email\":\"linonetwo012@gmail.com\",\"accessToken\":\"gho_e85FDD9sbzvUEHCd9...\"},\"defaultGitInfo\":{\"email\":\"tiddlygit@gmail.com\",\"gitUserName\":\"tiddlygit\"},\"logger\":{}}.\nerror: src refspec master does not match any\nerror: failed to push some refs to 'https://github.com/linonetwo/calendar.git'\n\n    at new t (/Applications/TiddlyGit.app/Contents/Resources/app.asar.unpacked/.webpack/main/webpack:/TiddlyGit/node_modules/git-sync-js/dist/errors.js:65:28)\n    at call (/Applications/TiddlyGit.app/Contents/Resources/app.asar.unpacked/.webpack/main/webpack:/TiddlyGit/node_modules/git-sync-js/dist/index.js:118:31)\n    at step (/Applications/TiddlyGit.app/Contents/Resources/app.asar.unpacked/.webpack/main/webpack:/TiddlyGit/node_modules/git-sync-js/dist/index.js:43:23)\n    at Object.next (/Applications/TiddlyGit.app/Contents/Resources/app.asar.unpacked/.webpack/main/webpack:/TiddlyGit/node_modules/git-sync-js/dist/index.js:24:53)\n    at a (/Applications/TiddlyGit.app/Contents/Resources/app.asar.unpacked/.webpack/main/webpack:/TiddlyGit/node_modules/git-sync-js/dist/index.js:15:58)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)","level":"crit","timestamp":"2021-09-20T11:48:41.262Z"}
{"function":"stopWiki","level":"warning","message":"No wiki for /Users/linonetwo/Desktop/calendar. No running worker, means maybe tiddlywiki server in this workspace failed to start","timestamp":"2021-09-20T11:48:41.285Z"}
{"function":"stopWatchWiki","level":"warning","message":"No wiki watcher for /Users/linonetwo/Desktop/calendar","timestamp":"2021-09-20T11:48:41.286Z"}
{"message":"subwiki/calendar changed, but lock is on, so skip","level":"info","timestamp":"2021-09-20T11:48:42.332Z"}

**Comment by linonetwo** [comment]
提供log会更好修

**Comment by linonetwo** [comment]
{"handler":"wiki-create-progress","level":"notice","message":"开始链接子Wiki到父Wiki","timestamp":"2021-09-20T17:39:42.824Z"}
{"handler":"wiki-create-progress","level":"notice","message":"在主Wiki内成功创建子Wiki的快捷方式，将文件存入主Wiki内的快捷方式会自动将文件存入子Wiki。","timestamp":"2021-09-20T17:39:42.827Z"}
{"handler":"wiki-create-progress","level":"notice","message":"正在为子Wiki添加FileSystemPaths","timestamp":"2021-09-20T17:39:42.827Z"}
{"handler":"wiki-create-progress","level":"notice","message":"子Wiki创建完毕","timestamp":"2021-09-20T17:39:42.828Z"}
{"handler":"wiki-create-progress","callerFunction":"initWikiGit","functionName":"initGit","step":"StartGitInitialization","level":"notice","message":"开始初始化本地 Git 仓库","timestamp":"2021-09-20T17:39:43.488Z"}
{"handler":"wiki-create-progress","callerFunction":"initWikiGit","functionName":"initGit","step":"StartConfiguringGithubRemoteRepository","level":"notice","message":"仓库初始化完毕，开始配置 Git 云端仓库","timestamp":"2021-09-20T17:39:44.849Z"}
{"handler":"wiki-create-progress","callerFunction":"initWikiGit","functionName":"initGit","step":"StartBackupToGitRemote","level":"notice","message":"正在将 Wiki 所在的本地 Git 备份到 Github 云端仓库，需要的时间取决于网速，请耐心等待","timestamp":"2021-09-20T17:39:45.323Z"}
{"message":"subwiki/calendar changed, but lock is on, so skip","level":"info","timestamp":"2021-09-20T17:39:46.971Z"}
{"handler":"wiki-create-progress","callerFunction":"initWikiGit","functionName":"initGit","step":"GitPushFailed","level":"notice","message":"Git上传的结果不佳，这通常意味着有网络问题","timestamp":"2021-09-20T17:39:48.558Z"}
{"message":"E-3 failed to config git to successfully pull from or push to remote with configuration {\"dir\":\"/Users/linonetwo/Desktop/calendar\",\"remoteUrl\":\"https://github.com/linonetwo/calendar\",\"syncImmediately\":true,\"userInfo\":{\"gitUserName\":\"linonetwo\",\"email\":\"linonetwo012@gmail.com\",\"accessToken\":\"gho_e85FDD9sbzvUEHCd9...\"},\"defaultGitInfo\":{\"email\":\"tiddlygit@gmail.com\",\"gitUserName\":\"tiddlygit\"},\"logger\":{}}.\nerror: src refspec master does not match any\nerror: failed to push some refs to 'https://github.com/linonetwo/calendar.git'\n","level":"error","timestamp":"2021-09-20T17:39:48.732Z"}
{"message":"↑Translated→: E-3 failed to config git to successfully pull from or push to remote with configuration {\"dir\":\"/Users/linonetwo/Desktop/calendar\",\"remoteUrl\":\"https://github.com/linonetwo/calendar\",\"syncImmediately\":true,\"userInfo\":{\"gitUserName\":\"linonetwo\",\"email\":\"linonetwo012@gmail.com\",\"accessToken\":\"gho_e85FDD9sbzvUEHCd9...\"},\"defaultGitInfo\":{\"email\":\"tiddlygit@gmail.com\",\"gitUserName\":\"tiddlygit\"},\"logger\":{}}.\nerror: src refspec master does not match any\nerror: failed to push some refs to 'https://github.com/linonetwo/calendar.git'\n","level":"error","timestamp":"2021-09-20T17:39:48.732Z"}
{"message":"initWikiGitTransaction failed, E-3 failed to config git to successfully pull from or push to remote with configuration {\"dir\":\"/Users/linonetwo/Desktop/calendar\",\"remoteUrl\":\"https://github.com/linonetwo/calendar\",\"syncImmediately\":true,\"userInfo\":{\"gitUserName\":\"linonetwo\",\"email\":\"linonetwo012@gmail.com\",\"accessToken\":\"gho_e85FDD9sbzvUEHCd9...\"},\"defaultGitInfo\":{\"email\":\"tiddlygit@gmail.com\",\"gitUserName\":\"tiddlygit\"},\"logger\":{}}.\nerror: src refspec master does not match any\nerror: failed to push some refs to 'https://github.com/linonetwo/calendar.git'\n GitPullPushError: E-3 failed to config git to successfully pull from or push to remote with configuration {\"dir\":\"/Users/linonetwo/Desktop/calendar\",\"remoteUrl\":\"https://github.com/linonetwo/calendar\",\"syncImmediately\":true,\"userInfo\":{\"gitUserName\":\"linonetwo\",\"email\":\"linonetwo012@gmail.com\",\"accessToken\":\"gho_e85FDD9sbzvUEHCd9...\"},\"defaultGitInfo\":{\"email\":\"tiddlygit@gmail.com\",\"gitUserName\":\"tiddlygit\"},\"logger\":{}}.\nerror: src refspec master does not match any\nerror: failed to push some refs to 'https://github.com/linonetwo/calendar.git'\n\n    at /Applications/TiddlyGit.app/Contents/Resources/app.asar.unpacked/.webpack/main/webpack:/TiddlyGit/node_modules/git-sync-js/dist/index.js:49:15","level":"crit","timestamp":"2021-09-20T17:39:48.733Z"}
{"function":"stopWiki","level":"warning","message":"No wiki for /Users/linonetwo/Desktop/calendar. No running worker, means maybe tiddlywiki server in this workspace failed to start","timestamp":"2021-09-20T17:39:48.756Z"}
{"function":"stopWatchWiki","level":"warning","message":"No wiki watcher for /Users/linonetwo/Desktop/calendar","timestamp":"2021-09-20T17:39:48.757Z"}
{"message":"subwiki/calendar changed, but lock is on, so skip","level":"info","timestamp":"2021-09-20T17:39:49.889Z"}

**Comment by linonetwo** [comment]
{"handler":"wiki-create-progress","callerFunction":"initWikiGit","functionName":"initGit","step":"StartBackupToGitRemote","level":"notice","message":"正在将 Wiki 所在的本地 Git 备份到 Github 云端仓库，需要的时间取决于网速，请耐心等待","timestamp":"2021-09-20T18:35:06.565Z"}
{"message":"subwiki/calendar changed, but lock is on, so skip","level":"info","timestamp":"2021-09-20T18:35:08.128Z"}
{"handler":"wiki-create-progress","callerFunction":"initWikiGit","functionName":"initGit","step":"GitPushFailed","level":"notice","message":"Git上传的结果不佳，这通常意味着有网络问题","timestamp":"2021-09-20T18:35:09.391Z"}
{"message":"E-3 failed to config git to successfully pull from or push to remote with configuration {\"dir\":\"/Users/linonetwo/Desktop/calendar\",\"remoteUrl\":\"https://github.com/linonetwo/calendar\",\"syncImmediately\":true,\"userInfo\":{\"gitUserName\":\"linonetwo\",\"email\":\"linonetwo012@gmail.com\",\"accessToken\":\"gho_e85FDD9sbzvUEHCd9...\"},\"defaultGitInfo\":{\"email\":\"tiddlygit@gmail.com\",\"gitUserName\":\"tiddlygit\"},\"logger\":{}}.\nmaster:master error: src refspec master does not match any\nerror: failed to push some refs to 'https://github.com/linonetwo/calendar.git'\n","level":"error","timestamp":"2021-09-20T18:35:09.394Z"}
{"message":"↑Translated→: E-3 failed to config git to successfully pull from or push to remote with configuration {\"dir\":\"/Users/linonetwo/Desktop/calendar\",\"remoteUrl\":\"https://github.com/linonetwo/calendar\",\"syncImmediately\":true,\"userInfo\":{\"gitUserName\":\"linonetwo\",\"email\":\"linonetwo012@gmail.com\",\"accessToken\":\"gho_e85FDD9sbzvUEHCd9...\"},\"defaultGitInfo\":{\"email\":\"tiddlygit@gmail.com\",\"gitUserName\":\"tiddlygit\"},\"logger\":{}}.\nmaster:master error: src refspec master does not match any\nerror: failed to push some refs to 'https://github.com/linonetwo/calendar.git'\n","level":"error","timestamp":"2021-09-20T18:35:09.394Z"}
{"message":"initWikiGitTransaction failed, E-3 failed to config git to successfully pull from or push to remote with configuration {\"dir\":\"/Users/linonetwo/Desktop/calendar\",\"remoteUrl\":\"https://github.com/linonetwo/calendar\",\"syncImmediately\":true,\"userInfo\":{\"gitUserName\":\"linonetwo\",\"email\":\"linonetwo012@gmail.com\",\"accessToken\":\"gho_e85FDD9sbzvUEHCd9...\"},\"defaultGitInfo\":{\"email\":\"tiddlygit@gmail.com\",\"gitUserName\":\"tiddlygit\"},\"logger\":{}}.\nmaster:master error: src refspec master does not match any\nerror: failed to push some refs to 'https://github.com/linonetwo/calendar.git'\n GitPullPushError: E-3 failed to config git to successfully pull from or push to remote with configuration {\"dir\":\"/Users/linonetwo/Desktop/calendar\",\"remoteUrl\":\"https://github.com/linonetwo/calendar\",\"syncImmediately\":true,\"userInfo\":{\"gitUserName\":\"linonetwo\",\"email\":\"linonetwo012@gmail.com\",\"accessToken\":\"gho_e85FDD9sbzvUEHCd9...\"},\"defaultGitInfo\":{\"email\":\"tiddlygit@gmail.com\",\"gitUserName\":\"tiddlygit\"},\"logger\":{}}.\nmaster:master error: src refspec master does not match any\nerror: failed to push some refs to 'https://github.com/linonetwo/calendar.git'\n\n    at /Applications/TiddlyGit.app/Contents/Resources/app.asar.unpacked/.webpack/main/webpack:/TiddlyGit/node_modules/git-sync-js/dist/index.js:49:15\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)","level":"crit","timestamp":"2021-09-20T18:35:09.394Z"}
{"function":"stopWiki","level":"warning","message":"No wiki for /Users/linonetwo/Desktop/calendar. No running worker, means maybe tiddlywiki server in this workspace failed to start","timestamp":"2021-09-20T18:35:09.411Z"}
{"function":"stopWatchWiki","level":"warning","message":"No wiki watcher for /Users/linonetwo/Desktop/calendar","timestamp":"2021-09-20T18:35:09.411Z"}
{"message":"subwiki/calendar changed, but lock is on, so skip","level":"info","timestamp":"2021-09-20T18:35:10.543Z"}

**Comment by linonetwo** [comment]
可以试试 https://github.com/tiddly-gittly/TiddlyGit-Desktop/releases/tag/v0.5.1-prerelease1
