### ISSUE TITLE
bug: 创建新wiki后报错，选择不管后没看到在哪里新建文本（教程里说的加号）

### ISSUE THREAD

**Issue by SeyeeL** [tiddly-gittly/TiddlyGit-Desktop#109]
Windows 0.5.0
![b3fcc2ec9da5ead92c45b074c8b8d35](https://user-images.githubusercontent.com/71479570/134453071-ee9b51d2-2367-4767-a877-fea39b1ec5ed.png)
![image](https://user-images.githubusercontent.com/71479570/134453098-404ab7ef-ba33-458d-81c8-db8c8ea928dd.png)

**Comment by linonetwo** [comment]
你要不试试那个预发布版，5.0.1-prerelease，就是发布里面最新的那个，如果还不行的话，我周末试着复现一下。

**Comment by SeyeeL** [comment]
> 你要不试试那个预发布版，5.0.1-prerelease，就是发布里面最新的那个，如果还不行的话，我周末试着复现一下。

是0.5.1吧哈哈哈，我试试

**Comment by SeyeeL** [comment]
还是一样的 @linonetwo 新建完是一样的提示，说不是wiki文件夹

**Comment by linonetwo** [comment]
oh，行，我这次只在 Mac 上测试了，我测一下 windows

**Comment by linonetwo** [comment]
@SeyeeL 我无法复现，你还是带上log吧，在设置-开发者工具里可以找到文件夹入口

没 log 不知道你那发生了啥

**Comment by linonetwo** [comment]
![image](https://user-images.githubusercontent.com/3746270/134766835-43cd441e-65ea-444e-b076-bc44eb3269ef.png)

我这正常的

**Comment by linonetwo** [comment]
{"message":"App booting","level":"info","timestamp":"2021-09-25T10:48:40.460Z"}
{"message":"buildMenu() failed: Error processing argument at index 2, conversion failure from  TypeError: Error processing argument at index 2, conversion failure from \n    at Object.normal (electron/js2c/browser_init.js:81:444)\n    at Object.insertItemByType (electron/js2c/browser_init.js:81:1392)\n    at Object.a.insert (electron/js2c/browser_init.js:81:3975)\n    at Object.a.append (electron/js2c/browser_init.js:81:3639)\n    at electron/js2c/browser_init.js:81:5657\n    at Array.forEach (<anonymous>)\n    at Function.a.buildFromTemplate (electron/js2c/browser_init.js:81:5607)\n    at new MenuItem (electron/js2c/browser_init.js:73:587)\n    at electron/js2c/browser_init.js:81:5664\n    at Array.forEach (<anonymous>)\n    at Function.a.buildFromTemplate (electron/js2c/browser_init.js:81:5607)\n    at qe.buildMenu (C:\\Users\\Administrator\\AppData\\Local\\TiddlyGit\\app-0.5.1-prerelease\\resources\\app.asar\\.webpack\\main\\webpack:\\TiddlyGit\\src\\services\\menu\\index.ts:65:20)\n[{\"id\":\"TiddlyGit\",\"submenu\":[{},{\"type\":\"separator\"},{},{\"accelerator\":\"CmdOrCtrl+,\"},{\"type\":\"separator\"},{\"accelerator\":\"CmdOrCtrl+Shift+N\"},{\"type\":\"separator\"},{\"role\":\"services\",\"submenu\":[]},{\"type\":\"separator\"},{\"role\":\"hide\"},{\"role\":\"hideOthers\"},{\"role\":\"unhide\"},{\"label\":null,\"role\":\"quit\"}]},{\"id\":\"Edit\",\"role\":\"editMenu\"},{\"id\":\"View\",\"submenu\":[{\"accelerator\":\"CmdOrCtrl+F\",\"enabled\":false},{\"accelerator\":\"CmdOrCtrl+G\",\"enabled\":false},{\"accelerator\":\"Shift+CmdOrCtrl+G\",\"enabled\":false},{\"label\":\"undefined (undefined)\",\"checked\":false},{\"type\":\"separator\"},{\"role\":\"reload\"},{\"role\":\"forceReload\"},{\"label\":\"Zoom\"},{\"role\":\"resetZoom\"},{\"role\":\"togglefullscreen\"},{\"role\":\"close\"}]},{\"id\":\"Language\"},{\"id\":\"History\",\"submenu\":[{\"accelerator\":\"Shift+CmdOrCtrl+H\",\"enabled\":false},{\"accelerator\":\"CmdOrCtrl+[\",\"enabled\":false},{\"accelerator\":\"CmdOrCtrl+]\",\"enabled\":false},{\"type\":\"separator\"},{\"accelerator\":\"CmdOrCtrl+L\",\"enabled\":false}]},{\"id\":\"Workspaces\",\"submenu\":[{\"accelerator\":\"CmdOrCtrl+Shift+]\",\"enabled\":false},{\"accelerator\":\"CmdOrCtrl+Shift+[\",\"enabled\":false},{\"type\":\"separator\"},{\"enabled\":false},{\"enabled\":false},{\"enabled\":false},{\"type\":\"separator\"},{},{\"accelerator\":\"CmdOrCtrl+Option+I\",\"enabled\":false}]},{\"id\":\"Workspaces\",\"submenu\":[]},{\"role\":\"windowMenu\",\"id\":\"Window\"},{\"role\":\"help\",\"id\":\"help\",\"submenu\":[{},{},{},{}]},{\"label\":\"Wiki\",\"submenu\":[{\"enabled\":false},{\"accelerator\":\"CmdOrCtrl+Alt+Shift+P\"}]}]","level":"error","timestamp":"2021-09-25T10:48:40.562Z"}
{"message":"zxWorker initialized","level":"info","timestamp":"2021-09-25T10:48:40.574Z"}
{"handler":"wiki-create-progress","level":"notice","message":"开始用模板创建Wiki","timestamp":"2021-09-25T10:48:46.738Z"}
{"handler":"wiki-create-progress","level":"notice","message":"模板Wiki复制完毕C:\\Users\\Administrator\\Desktop\\wiki","timestamp":"2021-09-25T10:48:46.747Z"}
{"name":"E-9 网页加载失败错误","message":"E-9 工作区对应的Wiki网页加载失败了，但即将重试 initialUrl: http://172.27.112.1:5212/, retryTimes: 0 ERR_CONNECTION_REFUSED (-102) loading 'http://172.27.112.1:5212/' Error: ERR_CONNECTION_REFUSED (-102) loading 'http://172.27.112.1:5212/'\n    at rejectAndCleanup (electron/js2c/browser_init.js:161:7387)\n    at Object.failListener (electron/js2c/browser_init.js:161:7600)\n    at Object.emit (events.js:388:22)","level":"error","timestamp":"2021-09-25T10:48:49.097Z"}
{"handler":"wiki-create-progress","callerFunction":"initWikiGit","functionName":"initGit","step":"StartGitInitialization","level":"notice","message":"开始初始化本地 Git 仓库","timestamp":"2021-09-25T10:48:49.448Z"}
{"handler":"wiki-create-progress","callerFunction":"initWikiGit","functionName":"initGit","step":"GitRepositoryConfigurationFinished","level":"notice","message":"Git 仓库配置完毕","timestamp":"2021-09-25T10:48:49.763Z"}
{"message":"无法找到之前还在该处的工作区Wiki文件夹！本应存在于此处的WIki文件夹可能被移走了，或该文件夹内没有Wiki！是否移除工作区？ C:\\Users\\Administrator\\Desktop\\wiki 该目录不是一个Wiki文件夹 \"C:\\Users\\Administrator\\Desktop\\wiki\"","level":"error","timestamp":"2021-09-25T10:48:49.768Z"}
{"name":"E-9 网页加载失败错误","message":"E-9 工作区对应的Wiki网页加载失败了，但即将重试 initialUrl: http://172.27.112.1:5212/, retryTimes: 1 ERR_CONNECTION_REFUSED (-102) loading 'http://172.27.112.1:5212/' Error: ERR_CONNECTION_REFUSED (-102) loading 'http://172.27.112.1:5212/'\n    at rejectAndCleanup (electron/js2c/browser_init.js:161:7387)\n    at Object.failListener (electron/js2c/browser_init.js:161:7600)\n    at Object.emit (events.js:388:22)","level":"error","timestamp":"2021-09-25T10:48:52.186Z"}

**Comment by linonetwo** [comment]
原来要发布出来的版本才有，开发的时候没报错

**Comment by linonetwo** [comment]
![Uploading image.png…]()

看起来是安装包有问题

**Comment by SeyeeL** [comment]
噢噢现在可以复现了是吗？

**Comment by SeyeeL** [comment]
@linonetwo 请问解决了吗

**Comment by linonetwo** [comment]
最近我翻墙流量用光了，没法在windows上调试这个了，得等国庆流量恢复了才能继续搞…

**Comment by linonetwo** [comment]
我现在只能在公司mac上翻墙了

**Comment by linonetwo** [comment]
修了一天，这个应该修复了 https://github.com/tiddly-gittly/TiddlyGit-Desktop/releases/tag/v0.5.1
