### ISSUE TITLE
bug: A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by atsuko0710** [tiddly-gittly/TiddlyGit-Desktop#111]
## Environment

Node Version: v14.15.3

OS (macOS, Windows, Linux) and Version: macOS Catalina 10.15.6

安装的 TiddlyGit-Desktop 有 v0.5.0 和 v0.4.5，都出现相同的问题

## Description:

![image](https://user-images.githubusercontent.com/18242693/134863399-28de437f-0e53-4c44-8b7b-9d43fb8d8b19.png)

**Comment by linonetwo** [comment]
注意看readme。拖进application文件夹
