### ISSUE TITLE
bug: Incomplete translation

### ISSUE THREAD

**Issue by ubuntupunk** [tiddly-gittly/TiddlyGit-Desktop#132]
## Environment

TiddlyGit (linux)
Version v0.6.0.

Electron Version: 15.2.0
Node Version: 16.5.0
Chromium Version: 94.0.4606.81

## Description:

Choose Language >> English
Create new wiki
Expect new wiki to be in English

## Additional Context

New wiki has incomplete translation from Chinese.
![tiddly](https://user-images.githubusercontent.com/246662/139523437-c2a222ee-e99c-411a-90e2-cf801267aa31.png)

**Comment by linonetwo** [comment]
Hi, switch tw's language is on my to-do list, currently you may have to do this manually.

This is TW built-in translation, you need to enable EN language pack, in the ControlPanel- plugins-language pack, sorry for the inconvenience.

<img width="738" alt="截屏2021-10-30 下午3 21 17" src="https://user-images.githubusercontent.com/3746270/139524266-117bfdaf-38af-411e-abfd-8791c0e41785.png">

**Comment by linonetwo** [comment]
And, yes, this can be regarded as a bug.

**Comment by linonetwo** [comment]
Hi, latest release can handle this!
