### ISSUE TITLE
bug:  missing 'Maintainer' field

### ISSUE THREAD

**Issue by ubuntupunk** [tiddly-gittly/TiddlyGit-Desktop#147]
On Ubuntu 20.04

```
dpkg: warning: parsing file '/var/lib/dpkg/status' near line 96814 package 'tiddlygit':  missing 'Maintainer' field
```

**Comment by linonetwo** [comment]
How to fix this?

**Comment by linonetwo** [comment]
I only use MacOS, so...

**Comment by ubuntupunk** [comment]
please see [debian-policy](
https://www.debian.org/doc/debian-policy/ch-binary.html#s-maintainer)

in the meantime, users can just edit `/var/lib/dpkg/status`

```
Package: tiddlygit
Status: install ok installed
Priority: optional
 Section: utils
Installed-Size: 371394
Maintainer: Tiddlygit Developers <email address here>
Architecture: amd64
Version: 0.6.0
```
[see fix missing maintainer field](
https://www.idownloadblog.com/2018/05/28/fix-missing-maintainer-error-cydia/
)

**Comment by ubuntupunk** [comment]
please see [debian-policy](https://www.debian.org/doc/debian-policy/ch-binary.html#s-maintainer)

in the meantime, users can just edit `/var/lib/dpkg/status`

```
Package: tiddlygit
Status: install ok installed
Priority: optional
 Section: utils
Installed-Size: 371394
Maintainer: Tiddlygit Developers <email address here>
Architecture: amd64
Version: 0.6.0
```
[see fix missing maintainer field](https://www.idownloadblog.com/2018/05/28/fix-missing-maintainer-error-cydia/)

**Comment by linonetwo** [comment]
Might fixed in https://github.com/tiddly-gittly/TiddlyGit-Desktop/releases/tag/v0.6.5-a1
