### ISSUE TITLE
feature: 下载可以直接用到Windows了吗

### ISSUE THREAD

**Issue by xinmokunshou** [tiddly-gittly/TiddlyGit-Desktop#23]
# Feature Request
**Specifications:**
- App Version:
- OS (macOS, Windows, Linux):Windows

**Description:**

**Additional Context**

**Comment by linonetwo** [comment]
还没好，我还在本地调试，因为有些上游依赖的别的项目不是很好用，会导致同步问题等。

等稳定了我在知乎会发布的，可以在知乎上关注一下。

**Comment by FSpark** [comment]
无意中发现了这个建设中的项目，十分惊喜！TiddlyWiki使用也有一段时间了，可惜入门门槛略高很多人没能探索它的奥妙，但愿桌面易用化后又能成功吸引一批使用者吧。持续关注中，加油

**Comment by xinmokunshou** [comment]
> 还没好，我还在本地调试，因为有些上游依赖的别的项目不是很好用，会导致同步问题等。
> 
> 等稳定了我在知乎会发布的，可以在知乎上关注一下。

关注了，加油！

**Comment by linonetwo** [comment]
现在基本功能应该好了，不过我只有 Mac 电脑， windows 没测过，有空拿女朋友电脑测测。
