### ISSUE TITLE
bug: 不能创建子知识库

### ISSUE THREAD

**Issue by klchen0112** [tiddly-gittly/TiddlyGit-Desktop#25]
## Description:

无法创建新知识库
## Steps to Reproduce:
windows下,使用默认模板创建新子知识库时
TypeError: Cannot read property 'notice' of undefined

**Comment by linonetwo** [comment]
子知识库目前还不是很实用，因为要手动配 `$:/config/FileSystemPaths`，类似 https://github.com/linonetwo/wiki/blob/cfdd7dbbf09ff6361e259eb8040048e06061c25f/Meme-of-LinOnetwo/plugins/linonetwo/private-tiddlers-in-private-repo/FileSystemPaths.tid

我之后会加入一个方便的插件来自动化它的配置。

不过这个 Cannot read property 'notice' of undefined 不应该，我有空看看，mac 下没啥问题。

你登录了吗，有选一个在线仓库来同步吗？

**Comment by linonetwo** [comment]
新版更好地支持子知识库了，你可以试试。

你是怎么创建的？子知识库应该是一个空的仓库。
