### ISSUE TITLE
feature: 安装TidGi开发与依赖环境的Q&A

### ISSUE THREAD

**Issue by Zacharia2** [tiddly-gittly/TiddlyGit-Desktop#292]
### Description 描述

# 在clone项目并搭建开发环境时遇到的问题、注意点及解决方案

1. 使用虚拟机安装原生的Linux环境是最简单有效且问题少的最佳选择。
2. 安装vm虚拟机、Linux Mint并安装nvm（nodejs版本管理器）Linux版nvm安装地址https://github.com/nvm-sh/nvm#installing-and-updating    如果出现安装完成nvm命令提示未找到，可以关闭当前窗口在打开一个（官网是这样说的，我试过没问题）。然后使用nvm安装nodejs（TidGi Version v0.7.9，Node Version: 16.15.0）
3. 在nodejs中安装node-gyp，需要先安装g++（建议使用官方源安装，wsl中使用第三方源可能会出现依赖问题无法安装）、python最新版、make，然后再使用node-gyp configure 配置它使它通过检查。
4. 修改npm源为淘宝源：https://blog.csdn.net/Aria_Miazzy/article/details/106187406

```
设置NPM/Electron国内源
npm config set registry https://registry.npm.taobao.org
npm config set disturl https://npm.taobao.org/dist
npm config set electron_mirror https://npm.taobao.org/mirrors/electron/

```

一定要看electron官方文档 了解调试，主线程与渲染线程，主线程与渲染线程之间的通信，主线程的生命周期。消息机制等概念。

**Comment by Zacharia2** [comment]
执行 npm rebuild 重构一下依赖。试试可不可行。

**Comment by linonetwo** [comment]
用 nvm use 就能使用 .nvmrc 里声明的版本了

然后安装依赖是 npm i

**Comment by linonetwo** [comment]
别的问题我都没遇到过，可能就是因为没有 npm i ？

**Comment by Zacharia2** [comment]
输入nvm use 提示无效版本。

**Comment by Zacharia2** [comment]
> 别的问题我都没遇到过，可能就是因为没有 npm i ？

每次都会使用它安装依赖，每次都会出现上面几种情况。。。( ๑ŏ ﹏ ŏ๑ )

**Comment by Zacharia2** [comment]
nvm use 16.15.0

npm i

错误，修错

npm i

错误，修错

依赖安装成功

npm start

非vscode，报错，试图修复，失败从来。

在vscode中 npm start  

报错模块不存在。。。(•̩̩̩̩＿•̩̩̩̩)

**Comment by Zacharia2** [comment]
![image](https://user-images.githubusercontent.com/32425955/199213555-e4d14050-5aab-4f1a-9b9d-15742c3d6a6c.png)

**Comment by Zacharia2** [comment]
PS C:\Users\Mxun\Desktop\TidGi-Desktop> npm rebuild
npm ERR! code 1
npm ERR! path C:\Users\Mxun\Desktop\TidGi-Desktop\node_modules\registry-js
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c prebuild-install || node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.1.0
npm ERR! gyp info using node@16.15.0 | win32 | x64
npm ERR! gyp info find Python using Python version 3.10.5 found at "D:\Software\Scoop\apps\python\current\python.exe"
npm ERR! gyp ERR! find VS 
npm ERR! gyp ERR! find VS msvs_version not set from command line or npm config
npm ERR! gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
npm ERR! gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details
npm ERR! gyp ERR! find VS looking for Visual Studio 2015
npm ERR! gyp ERR! find VS - not found
npm ERR! gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio
npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.
npm ERR! gyp ERR! find VS For more information consult the documentation at:
npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Could not find any Visual Studio installation to use
npm ERR! gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\Mxun\Desktop\TidGi-Desktop\node_modules\node-gyp\lib\find-visualstudio.js:122:47)
npm ERR! gyp ERR! stack     at C:\Users\Mxun\Desktop\TidGi-Desktop\node_modules\node-gyp\lib\find-visualstudio.js:75:16
npm ERR! gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Users\Mxun\Desktop\TidGi-Desktop\node_modules\node-gyp\lib\find-visualstudio.js:364:14)
npm ERR! gyp ERR! stack     at C:\Users\Mxun\Desktop\TidGi-Desktop\node_modules\node-gyp\lib\find-visualstudio.js:71:14
npm ERR! gyp ERR! stack     at C:\Users\Mxun\Desktop\TidGi-Desktop\node_modules\node-gyp\lib\find-visualstudio.js:385:16
npm ERR! gyp ERR! stack     at C:\Users\Mxun\Desktop\TidGi-Desktop\node_modules\node-gyp\lib\util.js:54:7
npm ERR! gyp ERR! stack     at C:\Users\Mxun\Desktop\TidGi-Desktop\node_modules\node-gyp\lib\util.js:33:16
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:406:5)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1092:16)
npm ERR! gyp ERR! System Windows_NT 10.0.19044
npm ERR! gyp ERR! command "D:\\Software\\Scoop\\apps\\nvm\\current\\nodejs\\nodejs\\node.exe" "C:\\Users\\Mxun\\Desktop\\TidGi-Desktop\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\Users\Mxun\Desktop\TidGi-Desktop\node_modules\registry-js
npm ERR! gyp ERR! node -v v16.15.0
npm ERR! gyp ERR! node-gyp -v v9.1.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Mxun\AppData\Local\npm-cache\_logs\2022-11-01T10_28_48_017Z-debug-0.log

**Comment by Zacharia2** [comment]
在我的电脑上估计是缺少了什么所以无法运行，调试也做不了。如果没有办法的话，那自己尝试增加导入单文件wiki的功能就只能出师未捷身先死了<(。_。)>

**Comment by Zacharia2** [comment]
不过如果浏览器可以运行这几个命令的话
$tw.commands.savewikifolder
$tw.commands.load
$tw.commands.rendertiddler

或许可以写个插件，用浏览器运行。不知道浏览器可以不可，感觉有点不行。

**Comment by Zacharia2** [comment]
或许可以抄一下别人的图片本地存储的插件

**Comment by Zacharia2** [comment]
用虚拟机试试？

**Comment by linonetwo** [comment]
% nvm use                      
Found '/Users/linonetwo/Desktop/repo/TiddlyGit-Desktop/.nvmrc' with version <v16>
Now using node v16.13.0 (npm v8.3.2)

这样可以的呀

**Comment by linonetwo** [comment]
这样，你先把 node_modules 删了，再重新 npm i

记得先配好 https://blog.csdn.net/Aria_Miazzy/article/details/106187406 https://blog.csdn.net/AkitoSilver/article/details/90372230 这些国内镜像，可能之前是安装失败了

**Comment by linonetwo** [comment]
哦对了，你在 windows 上，需要安装最新版的 visual studio 提供的各种编译环境，因为 node-gyp 会调用这些 c++  python 的东西来编译一些 c++ 写的库。

**Comment by linonetwo** [comment]
npm ERR! gyp ERR! find VS looking for Visual Studio 2015

说的是 Visual Studio ，不是 vscode

**Comment by Zacharia2** [comment]
三克油，林大大，下课去试试

**Comment by Zacharia2** [comment]
gyp ERR!与node-pre-gyp ERR!报错解决

https://zhuanlan.zhihu.com/p/345314156

**Comment by Zacharia2** [comment]
Windows配置依赖真的好难，vs2022、c++、python、nodejs环境都已经安装了，gyp还是不给过。

**Comment by Zacharia2** [comment]
嗯，感觉自己还是太嫩了，算了，不如使用nvm，一键式安装nodejs与TiddlyWiki。然后使用TiddlyWiki命令转换。

**Comment by Zacharia2** [comment]
Linux配置好或许比Windows强很多吧。

**Comment by Zacharia2** [comment]
一开始的想法是太记有nodejs环境，或许可以免去安装nodejs环境的步骤，使用太记的nodejs环境运行TiddlyWiki命令转换HTML版本与文件夹版本。

**Comment by Zacharia2** [comment]
整理一下相关的学到的资料链接：

javascript设计模式——命令模式：https://www.cnblogs.com/xiaohuochai/archive/2017/12/14/8034617.html

electron 渲染进程（web 页面）和主进程 通信 之（ipcMain,ipcRenderer）：https://www.jianshu.com/p/61bc90092320

**Comment by linonetwo** [comment]
现在报啥错

参考 [https://www.chenhuojun.com/2020/07/12/%E4%B8%BAnode-gyp%E9%85%8D%E7%BD%AE%E6%9C%AC%E5%9C%B0%E7%BC%96%E8%AF%91%E7%8E%AF%E5%A2%83/](https://www.chenhuojun.com/2020/07/12/%E4%B8%BAnode-gyp%E9%85%8D%E7%BD%AE%E6%9C%AC%E5%9C%B0%E7%BC%96%E8%AF%91%E7%8E%AF%E5%A2%83/) 检查一下环境

**Comment by linonetwo** [comment]
现在唯一的问题就是 node gyp 的了吧

**Comment by Zacharia2** [comment]
可以装一个试试看

**Comment by Zacharia2** [comment]
主要是说配置文件不存在

**Comment by linonetwo** [comment]
是说类似  Please verify that the package.json has a valid "main" entry 这种吗，这就是 npm i
 的过程没装好，可能就是 node-gyp 没成功，就是因为它的环境依赖还没满足

**Comment by linonetwo** [comment]
所以很多前端开发者还是选择用 mac 或者 linux …

**Comment by Zacharia2** [comment]
![2019180634-614b1179e8109](https://user-images.githubusercontent.com/32425955/199657995-f6d4c6fa-f500-4b77-b925-116d91fa7716.png)
这是在网上找的，类似这种的错误。
上午刚刚把wsl安装好。

**Comment by linonetwo** [comment]
node-gyp 在 linux 环境下比较好配，注意准备好各种环境再 npm i 或者 rebuild

**Comment by Zacharia2** [comment]
nvm use在新的Linux中需要指定具体的nodejs版本，默认使用此版本的最新版。
Found '/mnt/c/Users/Mxun/Desktop/TidGi-Desktop/.nvmrc' with version <v16>
Now using node v16.18.0 (npm v8.19.2)
Creating default alias: default -> v16 (-> v16.18.0)

v16.18.0版本过于新了，无法安装依赖。在Windows中执行nvm use没反应。

**Comment by linonetwo** [comment]
windows 的 nvm 和 linux 的不一样，可能需要先 nvm install v16

**Comment by Zacharia2** [comment]
npm i
npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /mnt/c/Users/Mxun/Desktop/TidGi-Desktop/node_modules/ajv-formats
npm ERR! dest /mnt/c/Users/Mxun/Desktop/TidGi-Desktop/node_modules/.ajv-formats-uGLUafrW
npm ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty, rename '/mnt/c/Users/Mxun/Desktop/TidGi-Desktop/node_modules/ajv-formats' -> '/mnt/c/Users/Mxun/Desktop/TidGi-Desktop/node_modules/.ajv-formats-uGLUafrW'

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-11-03T13_15_00_858Z-debug-0.log

**Comment by Zacharia2** [comment]
node-gyp单独全局安装成功了。

**Comment by Zacharia2** [comment]
有时候执行会卡死在 idealTree: timing idealTree Completed in

**Comment by Zacharia2** [comment]
![image](https://user-images.githubusercontent.com/32425955/199735646-1b57654d-d7bc-418d-b2a7-0d9fbe8a7b43.png)

**Comment by linonetwo** [comment]
idealTree 的时候要等，杀了之后就会出错，得删掉 nodemodules 重装了

开始 npm i 之前一定要配好代理

**Comment by linonetwo** [comment]
你可以看网络情况，它其实是在下载东西和梳理

**Comment by Zacharia2** [comment]
> 

删掉 nodemodules 重装好像可以使用这个命令 npm ci

**Comment by linonetwo** [comment]
那个会忽视 devdeps ，开发不能用

**Comment by Zacharia2** [comment]
> 你可以看网络情况，它其实是在下载东西和梳理

卡死期间好像没有流量

**Comment by Zacharia2** [comment]
可能是学校网络速度太慢了吧，不想安装依赖了，呜呜呜，太难了，等假期回家试试看。谢谢林大大指点

**Comment by Zacharia2** [comment]
补充nodejs的node-gyp，，Python2，c/c++编译器gcc

**Comment by linonetwo** [comment]
那可能是需要翻，或者配上各种源，参考上面发的 #292

**Comment by Zacharia2** [comment]
改用yarn install可以解决idealTree: timing idealTree Completed in 756ms的卡死问题

**Comment by Zacharia2** [comment]
gyp: binding.gyp not found (cwd: /mnt/c/Users/Mxun/Desktop/TidGi-Desktop) while trying to load binding.gyp

**Comment by linonetwo** [comment]
可以先用 yarn ，别把 yarnlock 提交上来就行。

gyp 相关出问题，最简单就是删了 nodemodules 里相关的库然后重新 npm i

在 wsl2 里配会简单很多。我自己的 windows 上没遇到过这些问题，因为我是先配好了环境才开始安装的吧。

**Comment by Zacharia2** [comment]
> 可以先用 yarn ，别把 yarnlock 提交上来就行。
> 
> gyp 相关出问题，最简单就是删了 nodemodules 里相关的库然后重新 npm i
> 
> 在 wsl2 里配会简单很多，linux自带很多开发环境。我自己的 windows 上没遇到过这些问题，因为我是先配好了环境才开始安装的吧。

已经解决了，显示ok。还是得先安装gyp呀，使它的配置显示ok。binding.gyp文件缺失的问题按照上面的链接给的新建一个文件，填上一些东西就好了。

**Comment by Zacharia2** [comment]
好像全部都通过了。。。

**Comment by Zacharia2** [comment]
真的全部通过了。
![image](https://user-images.githubusercontent.com/32425955/199976705-720688b3-590a-42a9-ab1e-e1cde4144055.png)

**Comment by linonetwo** [comment]
代码上还有啥问题吗

**Comment by Zacharia2** [comment]
看了几天代码，自己使用调试理解了一下
1. 我发现林大大是使用nodejs 的TiddlyWiki模块加载的TiddlyWiki文件夹。所以我也可以使用这个，直接执行保存到文件夹的命令。
2. 我的想法是：在添加工作区wiki的窗口添加一个导入WIKI.HTMl选项卡，在这里获取到用户想要打开的Wiki.HTML和想要保存TiddlyWiki的文件夹。
3. 然后使用nodejs的TiddlyWiki模块解压Wiki.HTML并保存到用户输入的文件夹路径，解压完成之后使用TidGi也就是林大大写的接口加载解压后的TiddlyWiki文件夹。

不知道这样可不可行呢？

**Comment by linonetwo** [comment]
那个其实不用修，因为消失了不就白填了嘛，那个token是存储在配置里的，之后同步笔记还会用到的。

记得先像新建工作区一样，调 useNewWiki，或者你直接复用这个按钮，只是在useNewWiki里做一下判断 https://github.com/tiddly-gittly/TidGi-Desktop/blob/6fdf992c6a21feb722f8569d9b2554776ea68c99/src/pages/AddWorkspace/NewWikiDoneButton.tsx#L25

这里调的 window.service.wiki.copyWikiTemplate https://github.com/tiddly-gittly/TidGi-Desktop/blob/6fdf992c6a21feb722f8569d9b2554776ea68c99/src/pages/AddWorkspace/useNewWiki.ts#L75

可以根据一个 if 改为调 window.service.wiki.extractWikiHTML 之类的，这个函数加在  https://github.com/tiddly-gittly/TidGi-Desktop/blob/master/src/services/wiki/index.ts 里面，并在 interface 和 WikiServiceIPCDescriptor 里都注册之后，就能在前端那边调用了 https://github.com/tiddly-gittly/TidGi-Desktop/blob/6fdf992c6a21feb722f8569d9b2554776ea68c99/src/services/wiki/interface.ts#L14-L102

**Comment by linonetwo** [comment]
慢慢来，你可以先把 UI 弄好，然后 service 具体函数里就加个 console log，先把点击触发 service 的流程跑通，再去写具体的 extractWikiHTML 的功能，这样从 UI 出发会比较有成就感

**Comment by Zacharia2** [comment]
做好一个输入框，可以接受数据并保存在state里面。按钮还没搞定。

![image](https://user-images.githubusercontent.com/32425955/201329580-7039087d-27de-49e3-ba1f-69e4ff354ef2.png)

**Comment by Zacharia2** [comment]
现在已经可以执行解压HTML.WIKI的命令啦。按照林大大的指示做的，真的太棒了！谢谢林大大。

**Comment by Zacharia2** [comment]
{"level":"error","message":"Tiddlywiki booted failed with error Cannot read properties of undefined (reading 'substr') TypeError: Cannot read properties of undefined (reading 'substr')\n    at Object.exports.createDirectory ($:/core/modules/utils/filesystem.js:114:13)\n    at new FileSystemAdaptor ($:/plugins/tiddlywiki/filesystem/filesystemadaptor.js:25:12)\n    at $:/core/modules/startup.js:119:22\n    at /home/whitefall/桌面/TidGi-Desktop/node_modules/@tiddlygit/tiddlywiki/boot/boot.js:919:3\n    at Object.$tw.utils.each (/home/whitefall/桌面/TidGi-Desktop/node_modules/@tiddlygit/tiddlywiki/boot/boot.js:155:12)\n    at Object.$tw.modules.forEachModuleOfType (/home/whitefall/桌面/TidGi-Desktop/node_modules/@tiddlygit/tiddlywiki/boot/boot.js:918:12)\n    at Object.exports.startup ($:/core/modules/startup.js:117:14)\n    at Object.$tw.boot.executeNextStartupTask (/home/whitefall/桌面/TidGi-Desktop/node_modules/@tiddlygit/tiddlywiki/boot/boot.js:2536:10)\n    at Object.$tw.boot.executeNextStartupTask (/home/whitefall/桌面/TidGi-Desktop/node_modules/@tiddlygit/tiddlywiki/boot/boot.js:2540:21)\n    at Object.$tw.boot.executeNextStartupTask (/home/whitefall/桌面/TidGi-Desktop/node_modules/@tiddlygit/tiddlywiki/boot/boot.js:2540:21)","timestamp":"2022-11-11T13:33:56.360Z"}

**Comment by Zacharia2** [comment]
再完善流程和UI的逻辑就OK了

**Comment by Zacharia2** [comment]
{"level":"error","message":"Tiddlywiki booted failed with error Cannot read properties of undefined (reading 'replace') 
TypeError: Cannot read properties of undefined (reading 'replace')
 at Object.exports.generateTiddlerFilepath ($:/core/modules/utils/filesystem.js:344:23)
 at Object.exports.generateTiddlerFileInfo ($:/core/modules/utils/filesystem.js:278:32)
 at WikiFolderMaker.saveTiddler ($:/core/modules/commands/savewikifolder.js:168:27)
 at $:/core/modules/commands/savewikifolder.js:156:8
 at Object.$tw.utils.each (/home/whitefall/桌面/TidGi-Desktop/node_modules/@tiddlygit/tiddlywiki/boot/boot.js:155:12)
 at WikiFolderMaker.saveCustomPlugin ($:/core/modules/commands/savewikifolder.js:155:12)
 at $:/core/modules/commands/savewikifolder.js:99:12
 at Object.$tw.utils.each (/home/whitefall/桌面/TidGi-Desktop/node_modules/@tiddlygit/tiddlywiki/boot/boot.js:146:12)
 at WikiFolderMaker.save ($:/core/modules/commands/savewikifolder.js:79:12)
 at Command.execute ($:/core/modules/commands/savewikifolder.js:39:25)","timestamp":"2022-11-12T03:12:43.276Z"}

**Comment by linonetwo** [comment]
我一看怎么会有 Cannot read properties of undefined 这种错，在 TS 时代是基本不会有这种报错的。

原来是 tw 那边的 js 代码的问题啊，那可以看看它源码，一步步看一下，是不是什么参数少传了。

**Comment by linonetwo** [comment]
substr 和 replace 都是 string 上的函数，所以估计是某个应该传字符串的参数，没传，变成了 undefined 空值。

**Comment by linonetwo** [comment]
目前这个 UI是可以的，不过要记得用文件夹名作为工作区的名字

**Comment by Zacharia2** [comment]
> 我一看怎么会有 Cannot read properties of undefined 这种错，在 TS 时代是基本不会有这种报错的。
> 
> 原来是 tw 那边的 js 代码的问题啊，那可以看看它源码，一步步看一下，是不是什么参数少传了。

```
#!/usr/bin/env node

/*
This is invoked as a shell script by NPM when the `tiddlywiki` command is typed
*/

var $tw = require("./boot/boot.js").TiddlyWiki();

// Pass the command line arguments to the boot kernel
$tw.boot.argv = Array.prototype.slice.call(process.argv,2);

// Boot the TW5 app
$tw.boot.boot();
···

这个是tiddlywiki.js，nodejs，tiddlywiki模块里面的。
我尝试使用终端在模块的目录中执行这个命令也失败了：node tiddlywiki --load /home/whitefall/桌面/mNote.html --savewikifolder /home/whitefall/桌面/mNote

**Comment by linonetwo** [comment]
你可以到 nodemodules 里看这个源码的位置，在nodemodules里找到 tiddlywiki 文件夹，然后看 里面的 /core/modules/utils/filesystem.js

TypeError: Cannot read properties of undefined (reading 'replace')
at Object.exports.generateTiddlerFilepath ($:/core/modules/utils/filesystem.js:344:23)

就是报错栈里的这个文件，打log一层层看，我平时就这样看 tw 的调用问题的

**Comment by linonetwo** [comment]
还有在太记里，tw相关操作你可以写到 https://github.com/tiddly-gittly/TidGi-Desktop/blob/master/src/services/wiki/wikiWorker.ts 里，类似 startNodeJSWiki 这个函数，你加一个新的函数，然后加到底部 const wikiWorker = { startNodeJSWiki,  那边，就可以在外面使用了。

把对 tw 的操作放到这里，就算报错崩溃了也不会导致太记app崩溃。

如果你不熟悉这个的调用，可以先写个空函数，里面打log看看调用成功了没

**Comment by Zacharia2** [comment]
谢谢林大大，我试试这样做。

**Comment by Zacharia2** [comment]
我发现在Windows上还是Linux上执行`tiddlywiki --load ./mywiki.html --savewikifolder ./mywikifolder` 都会报错。说Cannot read properties of undefined (reading 'replace')

**Comment by linonetwo** [comment]
也就是说是这个 ./mywiki.html 里面有问题吧，反正有报错就看源码，看看具体是啥问题，也可能是 tiddlywiki 的问题，没法处理这个 html。

**Comment by Zacharia2** [comment]
是的有的tiddlywiki里面有问题，没法处理。

**Comment by Zacharia2** [comment]
![image](https://user-images.githubusercontent.com/32425955/201502213-55bd1a37-b491-4d16-aaa9-d4227c968c8e.png)

成功了，终于可以跑通整个流程了。

**Comment by Zacharia2** [comment]
剩下的工作就是补全代码。然后检查单文件wiki里面哪些插件或条目不能存在，是什么导致无法解压的问题。

**Comment by Zacharia2** [comment]
已经定位问题，只要这个插件存在就会出现转换错误。$:/plugins/Gk0Wk/notionpage-covericon

**Comment by linonetwo** [comment]
「方法中局部变量filepath 由 title参数赋值」其实看到这就差不多了吧，估计是它这插件少了个 title 参数？

**Comment by Zacharia2** [comment]
应该是这个问题。

**Comment by Gk0Wk** [comment]
啊这，key 都有 title 了，居然还要一个 title 字段吗，我觉得这个其实是 tw 的代码缺陷
