### ISSUE TITLE
bug: no input cursor when editing tiddler

### ISSUE THREAD

**Issue by fredguth** [tiddly-gittly/TiddlyGit-Desktop#30]
## Environment

TiddlyGit
Version v0.3.1.

Electron Version: 10.1.0

Node Version: 12.16.3

Chromium Version: 85.0.4183.87

## Description:

When editing a tiddler, the user can't see the input cursor.

https://share.getcloudapp.com/GGuR9gLQ

## Steps to Reproduce:
https://share.getcloudapp.com/GGuR9gLQ

**Comment by linonetwo** [comment]
Yes, this is strange... Only happened on the desktop, but not the browser.

Don't quite know the reason, but I will look into it.

**Comment by linonetwo** [comment]
Hi, a new fix in tw https://github.com/Jermolene/TiddlyWiki5/commit/543f9107b6a9de5fe13542fa30d9a4483d8b3eb8#commitcomment-42849656  fixes this.
