### ISSUE TITLE
feature: use github user to commit

### ISSUE THREAD

**Issue by fredguth** [tiddly-gittly/TiddlyGit-Desktop#31]
## Description:

When TiddlyGit commit changes to my wiki, the commits to github appear to have no author.  The continuous integration we have setup in Github, blocks any commit without author. I guess this user should be used due to the Github integration.

**Comment by linonetwo** [comment]
Yes, if this happen it will block the GitHub action to build the blog.

But I can see my commit surely is using my user info.

<img width="270" alt="截屏2020-09-15 上午10 14 53" src="https://user-images.githubusercontent.com/3746270/93157185-4d961000-f73c-11ea-92bf-a64a1119314e.png">


Can you attach the log (preference -> advanced -> open log folder -> copy&paste to pastebin) and show the git commit info in your wiki repo?

**Comment by linonetwo** [comment]
<img width="306" alt="Screen Shot 2020-10-11 at 8 33 08 PM" src="https://user-images.githubusercontent.com/3746270/95678711-faab5d80-0c00-11eb-8c46-08af9964b2d6.png">

Yeah, I agree something is wrong...Don't know why yet. Just add to the todo list.

**Comment by linonetwo** [comment]
![截屏2020-10-15 下午6 32 22](https://user-images.githubusercontent.com/3746270/96112140-c55e8280-0f14-11eb-9028-093a8a291e68.png)

Seems upon commit, you will use both the username of that token, and the local git user to commit.

**Comment by linonetwo** [comment]
I think latest version works fine https://github.com/tiddly-gittly/TiddlyGit-Desktop/releases/tag/v0.4.2-a5
