### ISSUE TITLE
bug: Can not continue

### ISSUE THREAD

**Issue by parse-code** [tiddly-gittly/TiddlyGit-Desktop#34]
## Environment

Version v0.3.4.

Electron Version: 12.0.0-nightly.20201026

Node Version: 14.14.0

Chromium Version: 88.0.4292.0

OS (macOS, Windows, Linux) and Version: MacOS Catalina 10.15.7 (19H2)

## Description:

When I click "+" and sign in with github, I have no idea what's the next step, I can not found active button to click:
![image](https://user-images.githubusercontent.com/350474/98892611-a9320f00-24db-11eb-984a-b695376b1837.png)

## Steps to Reproduce:
1. Download
2. Open App
3. No next

**Comment by hscui** [comment]
Me2,I dont know how to use it !

**Comment by JJJwan** [comment]
Me too!

**Comment by linonetwo** [comment]
I will make "login to github" optional in the next release, so you can just start using it without the need to sync to github.

**Comment by LuciaSn** [comment]
Me too with the latest version. Clicked on the button to get started then the same window appeared. Don't know how to create workspace.
![image](https://user-images.githubusercontent.com/76612630/103149859-aef06500-47a8-11eb-9b67-9f50f03fa0ff.png)

**Comment by linonetwo** [comment]
Okay, I'm doing a refactor to TS. The old code is a mess, and bugs come one by one, so I decided to do a clean up now...

**Comment by parse-code** [comment]
@linonetwo great work!

**Comment by Yansongsongsong** [comment]
so do i, but i have set the proxy, i have no idea to continue

**Comment by Yansongsongsong** [comment]
> so do i, but i have set the proxy, i have no idea to continue

even when i use the local mode

**Comment by linonetwo** [comment]
V0.4.0 is out, this may be fixed! Local mode is available!
