### ISSUE TITLE
feature:  other git services

### ISSUE THREAD

**Issue by greenbas** [tiddly-gittly/TiddlyGit-Desktop#35]
## Description:

I'd like to be able to sync my projects to my local gitea server for extra privacy. I understand why GitHub is the main focus, but it would still be good to be able to sync to other things, especially if the app is just syncing using git itself and not some sort of github exclusive API.

**Comment by linonetwo** [comment]
Sure, you can see I'm doing a refactor to typescript, I will support multiple storages later.

**Comment by Ziinc** [comment]
Is it possible to simply use the workspace's git configuration to auto commit and push to a repo? This way, any git service is technically supported. Sort of like how vscode detects a directory's git repo. 

note: I currently don't use tiddlygit (even though i want to) as my private tiddlywiki repo isn't hosted on Github, and I don't intend to migrate it to github either. TiddlyDesktop's folder support is too unstable for me to adtop it :disappointed:

**Comment by linonetwo** [comment]
V0.4.0 is out, this may be fixed! Local mode is available!

You can just create a local mode workspace, and configure the remote manually.
