### ISSUE TITLE
Question: Can I work on the wiki while on the move without using the desktop version?

### ISSUE THREAD

**Issue by dummifiedme** [tiddly-gittly/TiddlyGit-Desktop#37]
Is there a way I can use wiki via browser and save the edits over in the github?
With github saver we could do that but that was essentially a single-file wiki. 

I wanted to know if it would work with TG, will it help me have segmented files in my git (if at all TG allows to me to save my edits from a live browser.

**Comment by linonetwo** [comment]
To do so, we need a Github sync-adaptor, but currently no such sync-adaptor.

Only sync-adaptor can save tiddlers as separate files.

**Comment by linonetwo** [comment]
Another option, you can scan the QR code in your phone, and if your phone and PC that running TG is on the same wifi, you can use your phone to edit, and use TG to sync to the could.

**Comment by linonetwo** [comment]
<img width="661" alt="截屏2021-06-02 下午11 13 47" src="https://user-images.githubusercontent.com/3746270/120506162-3b5a2000-c3f8-11eb-8bdd-81fe6aaad36b.png">


<img width="916" alt="截屏2021-06-02 下午11 13 52" src="https://user-images.githubusercontent.com/3746270/120506131-34331200-c3f8-11eb-90ed-cb0ea7a49523.png">
