### ISSUE TITLE
bug: login with Github with empty access_token

### ISSUE THREAD

**Issue by suenchunyu** [tiddly-gittly/TiddlyGit-Desktop#38]
## Environment

Version: v0.3.4

Electron Version: 12.0.0-nightly.20201026

Node Version: 14.14.0

Chromium Version: 88.0.4292.0

OS (macOS, Windows, Linux) and Version: macOS Big Sur

## Description:

Click' Login Github Account' and log-in with Github OAuth authorization. After returning to TiddlyGit UI, it always shows 'Wait for Login' and credentials is always empty.

## Steps to Reproduce:

1. Open TiddlyGit.
2. Click 'Add' button.
3. Click 'Login Github Account'
4. Login with Github OAuth.
5. Reproduction!

**Comment by linonetwo** [comment]
被墙了吧，我最近在重构，之后支持gitlab和码云吧。

我都是翻墙的。

**Comment by FastStonewkx** [comment]
我使用了翻墙软件，问题是依旧不好登录，没有离线使用功能吗

**Comment by linonetwo** [comment]
这个月会发一版，允许离线使用吧，用本地 git 来备份和时光机还原应该也足够了

**Comment by FastStonewkx** [comment]
感谢

**Comment by linonetwo** [comment]
v0.4.0 is out, this may be fixed! Local mode is available.
