### ISSUE TITLE
bug: I can't open the app on a M1 mac

### ISSUE THREAD

**Issue by afenc** [tiddly-gittly/TiddlyGit-Desktop#45]
## Environment

OS (macOS, Windows, Linux) and Version: mac os 11.4

## Description:

After downloading the dmg file and installing it in the app folder, the iocn was added a blocked circle. See the attached img.

<img width="435" alt="Screen Shot 2021-05-29 at 13 04 02" src="https://user-images.githubusercontent.com/9139187/120058713-83d3af80-c07f-11eb-8d7b-92c508442f60.png">

I also cant find the "Open using Rosetta." option in the info section.

**Comment by linonetwo** [comment]
Okay, I will try to fix this in V0.4.1

**Comment by afenc** [comment]
I can unzip and copy v0.4.0 to the application folder, but it did not open and run. See issue #61

**Comment by linonetwo** [comment]
Try this https://github.com/tiddly-gittly/TiddlyGit-Desktop/releases/tag/v0.4.1-a2
