### ISSUE TITLE
bug: can't install the latest release on windows 10

### ISSUE THREAD

**Issue by Deteriorator** [tiddly-gittly/TiddlyGit-Desktop#50]
## Environment

Windows 10 

Electron Version: None

Node Version: None

Chromium Version: Chrome 90.0.4430.212

OS (macOS, Windows, Linux) and Version: Windows 10 20H2

## Description:

abort when install on windows, release is TiddlyGit-0.4.0

## Steps to Reproduce:

just double click to install the software

## Additional Context

![image](https://user-images.githubusercontent.com/31269745/120575477-bb61a380-c453-11eb-81e8-0fbeb0856324.png)

**Comment by linonetwo** [comment]
Oh strange, I can install on my win 10... Maybe you should quit 360

**Comment by Deteriorator** [comment]
> Oh strange, I can install on my win 10... Maybe you should quit 360

360 is not installed on my computer, because this computer is used for work in company

**Comment by linonetwo** [comment]
Oh, this means you successfully installed it, but it have problem starting, due to Menu building. It might be Menubar or context manu, I will check it out.

**Comment by Ziinc** [comment]
Occurs on both PopOS Ubuntu & Windows 10 (both machines I've tried it on) as well, right after installation.

![image](https://user-images.githubusercontent.com/22714384/121783170-d19ffa00-cbdf-11eb-9d74-cd01f5d67c84.png)

**Comment by chevyjiang** [comment]
![image](https://user-images.githubusercontent.com/86186836/122868615-c2e2e100-d35d-11eb-83cc-15e83f5e8dd6.png)

Edition	Windows 10 Enterprise
Version	20H2
Installed on	‎4/‎19/‎2021
OS build	19042.1052
Experience	Windows Feature Experience Pack 120.2212.2020.0

**Comment by linonetwo** [comment]
I think this is fixed in https://github.com/tiddly-gittly/TiddlyGit-Desktop/releases/tag/v0.4.1-a7

I add a try catch around these code

And installer requires me to do https://github.com/mongodb-js/electron-squirrel-startup which I didn't know before.
