### ISSUE TITLE
bug: Timeout: Did not receive an init message from worker after 10000ms. Make sure the worker calls expose().

### ISSUE THREAD

**Issue by TiddlyWorkspace** [tiddly-gittly/TiddlyGit-Desktop#55]
```
Error: Timeout: Did not receive an init message from worker after 10000ms. Make sure the worker calls expose().
    at Timeout._onTimeout (C:\Users\44377\AppData\Local\TiddlyGit\app-0.4.0\resources\app.asar\.webpack\main\index.js:2:1324935)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```

---

TiddlyGit 0.4.0
Electron 12.0.6
win32 10.0.18363
Locale: zh-CN

**Comment by linonetwo** [comment]
Okay, I will try in windows...But this should have been the same across Mac and Windows.

**Comment by linonetwo** [comment]
This happened in workspace creation, of a synced wiki? It might be a wiki worker or git worker, I need confirmation of this.

**Comment by linonetwo** [comment]
Hope this is fixed in the latest prerelease...

Cause might be the git-worker.
