### ISSUE TITLE
bug: Git could not be found at the expected path: 'C:\Users\Hue\Apps\TiddlyGit\node_modules\dugite\git\cmd\git.exe'. This might be a problem with how the application is packaged, so confirm this folder hasn't been removed when packaging.

### ISSUE THREAD

**Issue by HueLiu** [tiddly-gittly/TiddlyGit-Desktop#60]
If I keep the _wiki_ name as the default GitHub repository's name,  I could skip the blank page mentioned in the previous issue #56 .

However, when I try to close and reopen the app, the following error will be reported.

![image](https://user-images.githubusercontent.com/19755727/120919193-e87bb380-c6ea-11eb-9431-36477694f227.png)

```
Error: Git could not be found at the expected path: 'C:\Users\Hue\Apps\TiddlyGit\node_modules\dugite\git\cmd\git.exe'. This might be a problem with how the application is packaged, so confirm this folder hasn't been removed when packaging.
    at C:\Users\Hue\Apps\TiddlyGit\resources\app.asar.unpacked\.webpack\main\722.index.worker.js:2:11433
    at exithandler (child_process.js:324:5)
    at ChildProcess.errorhandler (child_process.js:336:5)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

---

TiddlyGit 0.4.0
Electron 12.0.6
win32 10.0.19043
Locale: zh-CN

**Comment by linonetwo** [comment]
May be fix via https://github.com/desktop/dugite/issues/96#issuecomment-309270786 , I will take a try.

**Comment by linonetwo** [comment]
I used to do https://github.com/electron/electron/issues/18540#issuecomment-660679649 in 0.3.x , may be the last option.

**Comment by linonetwo** [comment]
I think this is fixed in https://github.com/tiddly-gittly/TiddlyGit-Desktop/releases/tag/v0.4.1-a7

I add a config to fix it https://github.com/tiddly-gittly/TiddlyGit-Desktop/blob/2f51af59028051960727cb7bf46d87027421b289/webpack.plugins.js#L27
