### ISSUE TITLE
bug: 以管理员身份启动之后就弹出这个页面了

### ISSUE THREAD

**Issue by Ryan-Kong** [tiddly-gittly/TiddlyGit-Desktop#63]
![image](https://user-images.githubusercontent.com/23193966/122359403-19c86f00-cf88-11eb-849e-7dfa6a5fa828.png)
图二是系统配置页面
![image](https://user-images.githubusercontent.com/23193966/122359649-5005ee80-cf88-11eb-8ee5-4360157b9f54.png)
点击OK之后的错误页面
![image](https://user-images.githubusercontent.com/23193966/122359746-6318be80-cf88-11eb-92b2-db51d31d0b83.png)

**Comment by linonetwo** [comment]
I think this is fixed in https://github.com/tiddly-gittly/TiddlyGit-Desktop/releases/tag/v0.4.1-a7

I add a try catch around these code
