### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by XiaXia-z** [tiddly-gittly/TiddlyGit-Desktop#80]
![图片](https://user-images.githubusercontent.com/75313652/124793950-1588e380-df81-11eb-91ac-741004dcbdd2.png)

this is different from what's in MacOS

**Comment by linonetwo** [comment]
fixed also by https://github.com/tiddly-gittly/TiddlyGit-Desktop/commit/485845e339804ae6e9f7f245e6a485c56e2b224c
