### ISSUE TITLE
bug: 工作区对应的Wiki网页加载失败了，原因有很多，但基本是因为程序Bug ERR_CONNECTION_TIMED_OUT http://10.167.1.152:5212/#:GettingStart

### ISSUE THREAD

**Issue by chevyjiang** [tiddly-gittly/TiddlyGit-Desktop#83]
## Environment

TiddlyGit 0.4.1-a15
Electron 14.0.0-beta.12
win32 10.0.19042
Locale: en-US

## Additional Context

```typescript
工作区加载失败错误: 工作区对应的Wiki网页加载失败了，原因有很多，但基本是因为程序Bug ERR_CONNECTION_TIMED_OUT http://10.167.1.152:5212/#:GettingStarted
    at On.main [as initializeAllWorkspaceView] (C:\Users\coxcj\AppData\Local\TiddlyGit\app-0.4.1-a15\resources\app.asar\.webpack\main\webpack:\TiddlyGit\src\services\workspacesView\index.ts:81:15)
    at initRendererI18NHandler (C:\Users\coxcj\AppData\Local\TiddlyGit\app-0.4.1-a15\resources\app.asar\.webpack\main\webpack:\TiddlyGit\src\main.ts:117:42)
    at App.<anonymous> (C:\Users\coxcj\AppData\Local\TiddlyGit\app-0.4.1-a15\resources\app.asar\.webpack\main\webpack:\TiddlyGit\src\main.ts:164:11)
```

---

**Comment by linonetwo** [comment]
你直接访问 http://10.167.1.152:5212 是不是可以看到 wiki

**Comment by linonetwo** [comment]
Try  A-17 https://github.com/tiddly-gittly/TiddlyGit-Desktop/releases/tag/v0.4.1-a17

**Comment by chevyjiang** [comment]
1st try, direct install new version

  *   amazing thing happened, no any earning or error message, but still, no service, no main screen....

2nd try, uninstall, restart windows, and install new version

  *   same as 1st try...

log as attached

[cid:f0f94b88-3fd5-4be3-9d82-b8c67a9e6ab3]
________________________________
发件人: lin onetwo ***@***.***>
发送时间: 2021年7月20日 15:08
收件人: tiddly-gittly/TiddlyGit-Desktop ***@***.***>
抄送: chevyjiang ***@***.***>; Author ***@***.***>
主题: Re: [tiddly-gittly/TiddlyGit-Desktop] bug: 工作区对应的Wiki网页加载失败了，原因有很多，但基本是因为程序Bug ERR_CONNECTION_TIMED_OUT http://10.167.1.152:5212/#:GettingStart (#83)


Try A-17 https://github.com/tiddly-gittly/TiddlyGit-Desktop/releases/tag/v0.4.1-a17<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftiddly-gittly%2FTiddlyGit-Desktop%2Freleases%2Ftag%2Fv0.4.1-a17&data=04%7C01%7C%7C7be322ffac894627adae08d94b4d3d40%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637623617377984460%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=W5XtqPWryKntNdeSbnukMC5akaiG7RdhzGwzCC6t0Vg%3D&reserved=0>

―

**Comment by linonetwo** [comment]
No log is attached here.

Did you try remove wiki and recreate a local wiki?
