### ISSUE TITLE
bug: 页面空白

### ISSUE THREAD

**Issue by chevyjiang** [tiddly-gittly/TiddlyGit-Desktop#84]
环境
TiddlyGit (win32)
Version v0.4.1-a15.
Electron Version: 14.0.0-beta.12
Node Version: 14.17.0
Chromium Version: 93.0.4557.4_

问题见图，若干次出错，打开后，程序内部是空的。。。，可以正常打开设置等页面
![image](https://user-images.githubusercontent.com/86186836/126057026-b285504f-b3f5-4bd3-8145-d1b4700fda95.png)

**Comment by linonetwo** [comment]
这就奇怪了，你把 log 文件夹里的都发上来吧，设置里有打开 log 文件夹的按钮。

**Comment by chevyjiang** [comment]
直接访问10.167.1.152：5212无法打开

________________________________
发件人: lin onetwo ***@***.***>
发送时间: 2021年7月18日 14:05
收件人: tiddly-gittly/TiddlyGit-Desktop ***@***.***>
抄送: chevyjiang ***@***.***>; Author ***@***.***>
主题: Re: [tiddly-gittly/TiddlyGit-Desktop] bug: 页面空白 (#84)


这就奇怪了，你把 log 文件夹里的都发上来吧，设置里有打开 log 文件夹的按钮。

―

**Comment by linonetwo** [comment]
那说明 wiki 服务没有启动成功，不过你得提供更多信息，因为我这边都能成功启动的，我的windows上可以。

**Comment by chevyjiang** [comment]
服务名称叫什么?
我在系统服务中没有找到
类似Tiddly或者Git开头的
[cid:bfa2cffd-8fae-4956-9ce5-6f5ee4e5c208]
________________________________
发件人: lin onetwo ***@***.***>
发送时间: 2021年7月18日 18:11
收件人: tiddly-gittly/TiddlyGit-Desktop ***@***.***>
抄送: chevyjiang ***@***.***>; Author ***@***.***>
主题: Re: [tiddly-gittly/TiddlyGit-Desktop] bug: 页面空白 (#84)


那说明 wiki 服务没有启动成功，不过你得提供更多信息，因为我这边都能成功启动的，我的windows上可以。

―

**Comment by linonetwo** [comment]
不是系统服务，我是指这个app里的wiki worker 线程，可以看看log的情况，可能是创建流程等问题导致启动失败了。

**Comment by linonetwo** [comment]
是不是还有别的报错，我看是有点问题，晚上回去看看。

**Comment by linonetwo** [comment]
是不是还报了

Unhandled Promise Rejection
Error: Cannot find module '/Applications/TiddlyGit.app/Contents/Resources/node_modules/@tiddlygit/tiddlywiki/boot/boot.js'. Please verify that the package.json has a valid "main" entry
    at /Applications/TiddlyGit.app/Contents/Resources/app.asar.unpacked/.webpack/main/webpack:/TiddlyGit/external "@tiddlygit/tiddlywiki":1:38
    at /Applications/TiddlyGit.app/Contents/Resources/app.asar.unpacked/.webpack/main/543.index.worker.js:1:135332
    at Object.<anonymous> (/Applications/TiddlyGit.app/Contents/Resources/app.asar.unpacked/.webpack/main/543.index.worker.js:1:135336)

我这是有这个，这个才是关键信息。

**Comment by linonetwo** [comment]
可以试试最新的发布啊 https://github.com/tiddly-gittly/TiddlyGit-Desktop/releases/tag/v0.4.2-a1

**Comment by chevyjiang** [comment]
问题解决👍

发自我的iPad

在 2021年8月4日，02:05，lin onetwo ***@***.***> 写道：

﻿

可以试试最新的发布啊 https://github.com/tiddly-gittly/TiddlyGit-Desktop/releases/tag/v0.4.2-a1<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftiddly-gittly%2FTiddlyGit-Desktop%2Freleases%2Ftag%2Fv0.4.2-a1&data=04%7C01%7C%7Cc779a9a591ea468b89c508d956a93e95%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637636107162545088%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ZZ3SNnfdThOD6wb74PSg3ef5ZqTAxR611hmWcW1OfT8%3D&reserved=0>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftiddly-gittly%2FTiddlyGit-Desktop%2Fissues%2F84%23issuecomment-892052003&data=04%7C01%7C%7Cc779a9a591ea468b89c508d956a93e95%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637636107162555047%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=oo5Dw9gxuFqIP%2FV5kWNn51SDxDpgpCvxReOQ1gGj2DU%3D&reserved=0>, or unsubscribe<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAURRWVHOZUJMVQMYJYHQ6QLT3AVVVANCNFSM5ARZIAYQ&data=04%7C01%7C%7Cc779a9a591ea468b89c508d956a93e95%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637636107162555047%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=S5fuEPAT246ZazdGvJ66W2zlsBu3z4nn6MW%2F%2Br8ecoU%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Cc779a9a591ea468b89c508d956a93e95%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637636107162565003%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=M%2BQIksXba%2BHxMjK7l6nP8kTWHAwnF7VAcr7pgDZEs4Y%3D&reserved=0> or Android<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7C%7Cc779a9a591ea468b89c508d956a93e95%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637636107162565003%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ZZUTYQb7xsC3cYChAjhl52sPLA6nnWx8NJUUfonY27g%3D&reserved=0>.
