### ISSUE TITLE
feature: 端口服务开关 身份验证 本地备份 TW导入 自建Git

### ISSUE THREAD

**Issue by Darleey** [tiddly-gittly/TiddlyGit-Desktop#86]
## Environment

Version v0.4.1-a15.

Electron Version: 14.0.0-beta.12
Node Version: 14.17.0
Chromium Version: 93.0.4557.4

OS (macOS, Windows, Linux) and Version:

Windows and ...

## Description:
刚入手 TG，最近在各种云端存储方案中徘徊。感谢大佬的贡献，将我从 [Note Self](https://noteself.org/) 边缘拉了回来。
在坑里遇到了一些问题 ~

1. TGD 基于本地端口的服务功能似乎是默认打开就自动启动的，还能增加一个手动控制服务启动的开关？应用一打开就暴露于局域网内，在家里还好，在外面，就有点慌[目前我是用防火墙黑名单，但杀敌一千，自损八百] ~
1. 系统插件提供的身份认证功能在这里好像不管用 ~
1. 配置文件本地备份方案【比如说自定义备份数量，多了自动删除、或者类似于 TimeMachine 这种】？在 稀里糊涂的修改了系统，或者引入了不稳定的插件... 的情况下，小白[Like Me]想要恢复正常就比较困难 ~
1. 如何导入其它已经建好的单文件 TiddlyWiKi 呢？或者导入本 TW 先前导出的单文件？【这似乎也能成为一种备份方案】~
1. 表示很期待自定义 Git 的功能 ~

**Comment by linonetwo** [comment]
可以的，那我加个开关，开启时用 0.0.0.0 ，关了就用 127.0.0.1 启动

身份认证我因为都是在局域网用就不考虑了，在外面的话我基本就是看看自动部署的公开版本，隐私内容都只放在本地。（不过子wiki功能最近有点问题）

备份的话用 git 就好，直接用 sourcetree 、 github desktop 等软件打开创建的 wiki 文件夹就好

导入就直接把HTML拖进窗口就行

git就是官方版的，还想怎么自定义呢

**Comment by Darleey** [comment]
我设想是自己建 Git服务器 这种，完了能集成验证服务到 太记里[开放出部分服务端配置的部分]。感觉一旦操作要折腾死人，还是你说的用第三方Git管理工具更稳妥一些～

另外，大佬提供的模板里，如果开启了 视觉外观/工具栏/查看工具栏 里的 **收合栏** 项目，收合栏会向右偏移，完了还不能全部收纳。

最后个人观感上，链入…  / 此文件夹中的文件… / 此文件所在的文件夹 居中好狂妄，修改哪个文件可以治治它们 🤔

**Comment by linonetwo** [comment]
其实用自建 gitea 之类的也可以啊，直接建本地 git ，然后也用 github desktop 来管理，它可以同步到私有git的，你自己配好 remote 就行。

收合栏那个好像是有问题，我没咋用就没修，你要是修好了就把 css 贴这吧。右键检查元素可以查看元素的css。

此文件夹中的文件 不是没居中吗：
![截屏2021-07-27 23 31 32](https://user-images.githubusercontent.com/3746270/127182845-489233a8-168d-4db4-b6d9-bf406bc95a6c.png)

要改的话也是检查元素改，然后css可以放到这个文件
<img width="409" alt="截屏2021-07-27 23 32 20" src="https://user-images.githubusercontent.com/3746270/127182990-41e557eb-7f81-4711-b543-99330674a45a.png">

**Comment by Darleey** [comment]
博客的网页端在 Chrome Android & Windows 这俩平台上都是居中的～难道是最近我没更新 Chrome 的原因？

![Screenshot_20210728-004209.jpg](https://user-images.githubusercontent.com/7878586/127194000-de671ee2-2275-4c99-8df4-548f43209d3e.jpg)

**Comment by linonetwo** [comment]
移动端没试过，反正都是右键检查元素改

最新版出了，有空试试有没有bug啊
