### ISSUE TITLE
bug: 无法在 Ubuntu 20.04 中打开

### ISSUE THREAD

**Issue by Darleey** [tiddly-gittly/TiddlyGit-Desktop#88]
## Environment
ESXI 

TG Version v 0.4.1

Electron Version:14.0.0 beta. 12

Node Version: 14.17.0

Chromium Version: 93.0.4557.4

OS (macOS, Windows, Linux) and Version:
20.04 [Based on ESXI 6.7]
## Description:

在 Esxi[6.7] 中创建的 Ubuntu 虚拟机[20.04]中跑，打开 添加工作区|设置 模块时，弹出的窗口一片空白～

**Comment by linonetwo** [comment]
好的，我也搞个虚拟机看看

**Comment by linonetwo** [comment]
可以打开开发者工具看看，是不是和这个是一样的问题 https://github.com/tiddly-gittly/TiddlyGit-Desktop/issues/56#issuecomment-855356323

右键白屏的窗口可以打开开发者工具，里面的 console 里有详细前端报错

**Comment by Darleey** [comment]
看上去差不多 ~

![image](https://user-images.githubusercontent.com/7878586/127482601-4c53ebeb-49c9-4177-9297-753703745414.png)


BTW… 
我基于太记构想的本地化同步方案：基于淘汰的笔记本搭起来的 Homelab[ESXI... Ubuntu... ] ，在上面开一个 TiddlyGit 当 Server 来作为局域网内部设备间的碎片素材采集器。对于移动设备来说这特别方便 → 有了灵感就直接打开嵌在手机桌面的网页快捷方式，写东西/粘贴素材 随后趁热打铁 打上tag 保存归类，偶尔还能当跨平台粘贴板使，更不用担心数据上云这种隐私问题，结果在最后一步跪了，哈哈哈哈 ~

**Comment by linonetwo** [comment]
嗯，bug是要修的，虽然这个比较奇怪，得研究一下咋修。

我有时候也是内网手机扫码打开手机版编辑，内网是没问题的。不过其实你可以用主力的 windows 电脑来开着它呀

**Comment by Darleey** [comment]
目前我就是这样做的！但主力机也有打盹下班的时刻~ 比如说睡前冲浪突然发现了几条肥鱼，但是趁手的鱼叉又不在身边，这种时刻总是有些遗憾的。而且这台主力机操劳过度，上个星期刚刚大出血换了主板和电池，虽说现在用起来隐隐感觉到已经没有了原来的灵魂，但我还是想它再陪我多走两年 😢
倒是 Homelab ，因为之前一直想要搞 FreeNAS、旁路由[让机器们更有效率的留学]、家庭画廊博客··· 虽说一直筹备着，但一直没下决心，这两天终于趁着东风开搞了，哈哈 ~

**Comment by linonetwo** [comment]
可以看看 https://github.com/tiddly-gittly/TiddlyGit-Desktop/releases/tag/v0.4.2-a5 是不是修复了

**Comment by Darleey** [comment]
才看到这条，最近没法测试了。因为占用资源很高，导致风扇一直转，我前一阵把虚拟机删了～
后来在vps上试水了 tiddlywiki + node.js，加个密码验证来担任 临时中转站 就还不赖～
