### ISSUE TITLE
bug: 子知识库图标顺序调整会错乱 & 子知识库条目无法依既有tag自动归类

### ISSUE THREAD

**Issue by Darleey** [tiddly-gittly/TiddlyGit-Desktop#91]
## Environment

Version v0.4.1

Electron Version: 14.0.0-beta.12
Node Version: 14.17.0
Chromium Version: 93.0.4557.4

OS (macOS, Windows, Linux) and Version:

Windows 10

## Description
1. 子知识库的顺序调整很迷。在有一主知识库，多个子知识库的前提下，如果想要调整 子知识库对应图标在侧边栏的上下顺序时，各子知识库图标间会出现神秘的联动反应～

2. 如果 创建/调整 子知识库的时候，填入/修改成 已经存在的某个 tag，与该 tag 关联的 tiddler 并不能自动进入相应的文件夹，而是要点击每一个含有该标签的 tiddler 修改再确定之后，才能移动到对应子知识库的文件夹。

**Comment by linonetwo** [comment]
我还只有俩子知识库，我看可以正常上下拖动图标啊，你有问题录屏吗？

哦对了，你那个版本还有bug吧，得用最新版，重新下一个吧/

**Comment by linonetwo** [comment]
0.4.1 正式版了

**Comment by linonetwo** [comment]
你可以试试重启 wiki，看会不会变过去。如果不会的话，就说明 tw 没有这个功能，哈哈
