### ISSUE TITLE
feature: 自建内容tiddler 和系统 tiddler 分开

### ISSUE THREAD

**Issue by Darleey** [tiddly-gittly/TiddlyGit-Desktop#93]
## Environment

Version v0.4.1

Electron Version: 14.0.0-beta.12
Node Version: 14.17.0
Chromium Version: 93.0.4557.4

OS (macOS, Windows, Linux) and Version:

Windows 10

## Description:
从子知识库的目录设置中联想到的，如果 主知识库 也采用类似的方式，将系统插件等产生的 tiddler 和 普通内容的 tiddler 分开，那么 tiddlers 目录无疑会精简很多。

[我目前曲线救国的方案是：首先新建标签 `0-cache`的子知识库，完了默认新建 tiddler 的标签是 `0-cache`，如此新生成的tiddler 便能在单独的目录中产生了，再建立其它的主要主题子知识库与对应 `0-***` 标签。后续整理过程中，将`0-cache` 移除，再附上对应主题的 `0-***` 标签]

这样的话，就可以通过文件管理的方式实现对应主题子知识库的备份与迁移～

**Comment by linonetwo** [comment]
应该是可以的，改 filesystem path 就好，不过不知道会不会和现在用的子知识库标签冲突。

你可以试试 https://tiddlywiki.com/#Customising%20Tiddler%20File%20Naming 

https://github.com/OokTech/TW5-Bob/issues/130#issuecomment-642784918

类似 [is[system]removeprefix[$:/]addprefix[_system/]]


不过一般来说，可以把主题和配置做成插件呀，就像我的 itonnote 插件一样，这样就和其他 tiddler 分开了。

**Comment by Darleey** [comment]
这法子真好用！感谢感谢
