### ISSUE TITLE
bug: 快捷键 Ctrl + F 调用搜索功能后搜索框就消失，但布局占用依旧保持

### ISSUE THREAD

**Issue by Darleey** [tiddly-gittly/TiddlyGit-Desktop#95]
## Environment

Version v0.4.2.

Electron Version: 14.0.0-beta.19
Node Version: 14.17.0
Chromium Version: 93.0.4577.15

OS (macOS, Windows, Linux) and Version:
WIndows 10 21H1

## Description:

使用快捷键 Ctrl + F 在调用内置浏览器搜索[比如说检索当前页面某个词汇/插件]，如果当前输入法是微软内置的中文输入法，搜索框会在几秒内消失，同时左侧窗口消失，但布局依旧保持占用状态。

![image](https://user-images.githubusercontent.com/7878586/128805182-58cfa3e1-d1ee-4de5-a5dd-6bfac89d1ccb.png)

![image](https://user-images.githubusercontent.com/7878586/128805986-995c5d34-a707-4814-bd6c-adb8471b030d.png)

## Additional Context

感觉和微软中文输入法有关系，tiddlygit 似乎是因为失去焦点，造成布局卡死在搜索。

**Comment by linonetwo** [comment]
连左边的工作区列表页白了，说明是 JS 出错了，你在变白的区域右键打开开发者工具，然后打开 console 那个 tab 截个图看看报错是啥吧

**Comment by linonetwo** [comment]
这个我这Mac上复现不了

**Comment by Darleey** [comment]
即使没有触发输入法 Bug，直接在工作区打开开发者工具，也会导致工作区消失：

![image](https://user-images.githubusercontent.com/7878586/128842323-57c03ae3-d131-45a9-b805-8cf7a9bfd0fa.png)



触发输入法 Bug 后，再打开对应开发者工具，开发者窗口会停留在后方

![image](https://user-images.githubusercontent.com/7878586/128842082-388802de-b1c5-4412-b75b-9cd2d9ec1f32.png)



后通过弹窗获得以下信息：

![image](https://user-images.githubusercontent.com/7878586/128845130-8c8df467-0844-4876-8bcf-07b50fcc00cc.png)

---

BTW：现在偶尔也会触发键盘无法输入[中英文]，但鼠标可正常操作的情况，频率不是很高，没截存信息，下次触发时补发 ~

**Comment by linonetwo** [comment]
直接在工作区打开开发者工具，这样之后的报错信息应该不一样吧？

这个搜索的应该好修，我有空看看。

**Comment by Darleey** [comment]
破案了，贴错图了，我之前没留意到窗口左上角的小猫腻～

当在工作区打开开发者工具后，开发者工具是以相对于工作区的位置默认向左展开的，直接把工作区挤到视界之外了～我那会还以为开发者工具没有启动～

**Comment by linonetwo** [comment]
https://github.com/tiddly-gittly/TiddlyGit-Desktop/releases/tag/v0.4.3-a2  应该修好了

**Comment by Darleey** [comment]
可以了 ~
