### ISSUE TITLE
feature: windows defender 开启文件夹访问控制后，tiddlygit 中的数据无法写入磁盘 

### ISSUE THREAD

**Issue by Darleey** [tiddly-gittly/TiddlyGit-Desktop#96]
## Environment

TiddlyGit (win32)
Version v0.4.3-a2.

Electron Version: 14.0.0-beta.19
Node Version: 14.17.0
Chromium Version: 93.0.4577.15

OS (macOS, Windows, Linux) and Version:

Windows 10 21H1

## Description:

Windows 10 打开 windows defender 提供的 文件访问控制<类似于 mac 的 Hands off，防流氓软件偷窥> 功能后，tiddlygit 可以正常读取，但没有写入权限[数据只能存在后台 server 的缓存上，重启后新写入的数据消失]。

如果直接按照快捷方式对应的主程序 `TiddlyGit.exe` 加入白名单，也无法写入。只有将更深一层的目录中的主程序 `./app-***/TiddlyGit.exe` 加入白名单，才可以顺利实现写入。

我试了一下，如果直接从子目录 <`./app-***/TiddlyGit.exe`> 启动，程序也能正常运行的，主目录中的 `TiddlyGit.exe` 似乎是一个类似于启动器或者快捷方式一般的鸡肋存在。所以，子目录中的 TiddlyGit.exe 可不可以挪到外面来？每更新一次就要修改一次文件访问控制列表就挺麻烦的，要是一不留神忘了<比如今天>，小半天的功夫都会打水漂 ~

## Additional Context

<之前的版本中也许也是这样，至今才发现是因为我前一阵缩减磁盘目录，原来的文件访问控制设置成了摆设 (⊙﹏⊙)，修改后就遭遇了鬼打墙事件~>

**Comment by linonetwo** [comment]
那些结构都是自动生成的，我平时主要适配的是 MacOS ，我的 windows 只是游戏机…

这个访问控制是不是虚拟了一个文件系统，不然 TiddlyWiki 会因为写不了文件而报错的吧。

你说的 子目录 <./app-***/TiddlyGit.exe>  这个我没看懂，还是截个图吧，Mac 上是这样的，这是 Electron 的结构，我也不知道原理是啥。

![截屏2021-08-12 下午9 45 01](https://user-images.githubusercontent.com/3746270/129207729-aa4aead0-c4a4-4959-8f6e-69d9ea60b770.png)

其实可以搜搜怎么解决 文件访问控制 的问题吧，不然其它要写入文件的应用，比如 typora 不是也会有问题吗？Mac 上是会直接弹框问能能不能允许访问文件系统，直接一键允许就没问题了。

**Comment by Darleey** [comment]
被骗了，瘟到死 挂羊头卖狗肉，它的安全验证比较奇葩，准确的描述是 文件写入控制<我刚刚才发现>。任何程序都可以读取目录对应的文件，白名单只是在程序写入的时候才会验证身份。
![image](https://user-images.githubusercontent.com/7878586/129301407-b32d2bb0-3e6d-4501-9b74-249e677525a2.png)

完了 TiddlyGit 比较特殊一些，如果在运行过程中，写入权限突然没有了[比如说 文件“访问”控制 突然启动、或者被从白名单中移除]，它会继续写入浏览器缓存，但停止写入到本地，这种行为并不会触发权限报警通知<Typora 在运行过程中没有了写入权限，尝试保存到本地就会触发权限报警通知>。而等 TiddlyGit 拥有权限后，又能无声无息的将修改同步到本地。

万幸的是每次 TiddlyGit 启动的时候，如果没有写入权限，会触发报警通知。

Typora 的主目录是这样的，只要在第一次使用的时候，授权一次就可以了。
![image](https://user-images.githubusercontent.com/7878586/129299355-a81de425-4122-4c57-b269-e1ba9edeaf2a.png)

TiddlyGit 的主目录，有一个 `TigglyGit.exe`，快捷方式指向它，但实际上运行的并不是这一个。
![image](https://user-images.githubusercontent.com/7878586/129300979-83528d32-32a9-43be-8d22-9131b88fa347.png)

真正运行的 `TiddlyGit.exe` 所在位置，只有对这里面的 TiddlyGit.exe 授权文件才有本地写入权限。
![image](https://user-images.githubusercontent.com/7878586/129300923-9b8e7907-a345-4c5c-9671-0f2823c6563e.png)

**Comment by linonetwo** [comment]
> 它会继续写入浏览器缓存，但停止写入到本地

这个感觉可以给 TiddlyWiki 提一个 issue ，比如加一个启动参数让它一定要写到文件系统上，然后就触发报警，弹框出来之后应该点一下允许就 OK了吧？

**Comment by Darleey** [comment]
似乎可行，但 tiddlywiki 默认就是存储在浏览器中的，可能要对 tiddlywiki/TiddlyWeb 这个插件动刀子 ~

**Comment by linonetwo** [comment]
好像是的，不过 nodejs 版都依赖这个吧，也基本算是内置功能了。

提一个英文 issue 让官方修吧。

**Comment by linonetwo** [comment]
加一个启动参数那样
