### ISSUE TITLE
bug: 第一次打开tw在太记打开的窗口很小, 只在左上角区域. 需要f11 最大化才会恢复.

### ISSUE THREAD

**Issue by hkdiy** [tiddly-gittly/TiddlyGit-Desktop#97]
## Environment

TG Version v

Electron Version:

Node Version:

Chromium [Version:](url)

OS (macOS, Windows, Linux) and Version:

**Comment by linonetwo** [comment]
可以试试 https://github.com/tiddly-gittly/TiddlyGit-Desktop/releases/tag/v0.4.3-a3
